# Site settings
title: Derick 
email: olsonderick@gmail.com 
description:
baseurl: ""
url: "http://www.derickolson.com"
twitter_username: dericksaid 
github_username: dericko 
linkedin_username: olsonderick

# Configuration

# Build settings
markdown: kramdown
permalink: pretty
