# Site settings
title: Derick 
email: olsonderick@gmail.com 
description: Hi there! This site is home to my projects, interests, and various dabblings.
baseurl: ""
url: "http://www.derickolson.com"
twitter_username: dericksaid 
github_username: dericko 
linkedin_username: derickolson

# Build settings
markdown: kramdown
permalink: pretty
