# Site settings
title: Derick 
email: olsonderick@gmail.com
email_name: olsonderick 
description: "Hi there! My name's Derick Olson. I'm a student of languages (imperative, functional, figurative, semanto-phonetic)."
baseurl: ""
url: "http://www.derickolson.com"
twitter_username: dericksaid 
github_username: dericko 
linkedin_username: derickolson
highlighter: pygments

# Build settings
markdown: kramdown
permalink: pretty
