# Site settings
title: Derick Olson
email: hello@derickolson.com
description: "Hi there, my name's Derick. I'm a student of languages (imperative, functional, figurative, semanto-phonetic)."
baseurl: ""
url: "http://www.derickolson.com"
github_username:
linkedin_username:
highlighter: rouge

# Build settings
markdown: kramdown
permalink: pretty
