# Site settings
title: Derick Olson
email: hello@derickolson.com
description: "Hi there, I'm Derick Olson. Writer and student of languages (imperative, functional, figurative, semanto-phonetic)."
baseurl: ""
url: "http://www.derickolson.com"
github_username: dericko
linkedin_username: derickolson
highlighter: rouge

# Build settings
markdown: kramdown
permalink: pretty
